### ISSUE TITLE
command.json references a different (older?) `dcos spark` wheel than the Universe package

### ISSUE THREAD

**Issue by ssk2** [mesosphere/spark-build#1]
`"http://downloads.mesosphere.io.s3.amazonaws.com/dcos/spark/dcos_spark-0.3.3-py2.py3-none-any.whl"` in spark-build, versus `"https://s3.amazonaws.com/downloads.mesosphere.io/dcos/spark/dcos_spark-0.4.0_spark_1.5.0_multi_roles_v2_bin_2.4.0-py2.py3-none-any.whl"` in the Universe. 

Is this intentional?

https://github.com/mesosphere/spark-build/blob/master/package/command.json 
https://github.com/mesosphere/universe/blob/version-1.x/repo/packages/S/spark/4/command.json#L3

**Comment by skonto** [comment]
@susanxhuynh should we close this as it is old and universe has been updated?

**Comment by susanxhuynh** [comment]
Yes, this is a very old package from two years ago. Closing.
