### ISSUE TITLE
Spark job is put on Queue after scaling up the containers.

### ISSUE THREAD

**Issue by siva-balusu** [mesosphere/spark-build#105]
I have run the below basic commands in a shell script : 
dcos package install spark
sleep 100
dcos spark run --submit-args="--class org.apache.spark.examples.SparkPi https://catcluster.blob.core.windows.net/jars/spark-examples_2.10-1.5.0.jar"
sleep 180
dcos marathon app update spark instances=3
sleep 180
dcos spark run --submit-args="--class org.apache.spark.examples.SparkPi https://catcluster.blob.core.windows.net/jars/spark-examples_2.10-1.5.0.jar"

The First job runs fine and the instances are being scaled to 3 and again the job is submitted then but it stays on Queue forever.

Below is the info from Config.Json:
"DCOS_PACKAGE_REGISTRY_VERSION": "3.0",
    "DCOS_SERVICE_NAME": "spark",
    "DCOS_PACKAGE_FRAMEWORK_NAME": "spark",
    "DCOS_SERVICE_PORT_INDEX": "3",
    "DCOS_PACKAGE_VERSION": "1.0.6-2.0.2",
    "SPARK_URI": "https://downloads.mesosphere.com/spark/assets/spark-2.0.2-bin-2.6.tgz",
    "DCOS_PACKAGE_NAME": "spark",
    "DCOS_PACKAGE_IS_FRAMEWORK": "false"

The general logs can be found on the below URL:
http://termbin.com/4g9w

**Comment by digeler** [comment]
can you paste the spark version here : dcos spark --version

**Comment by siva-balusu** [comment]
dcos-spark version 0.5.19


________________________________

**Comment by siva-balusu** [comment]
dcos-spark version 0.5.19

**Comment by digeler** [comment]
Hi Siva,
can you deploy another instance of dcos and see if the issue happens there -it seems that we have and issue with versions <dcos 1.8.7
in order to deploy the latest version you need to use the following :
this will create a new template with 1.8.7 
https://github.com/Azure/acs-engine
let me know if you need help with this.

**Comment by digeler** [comment]
hi Siva ,the template is here :
https://github.com/digeler/dcosnewversion/tree/master/_output
just press on the deploy to azure and fill in the details.
let me know how it wen

**Comment by siva-balusu** [comment]
I have deployed dcos.version 1.8.7. And still the problem persists. I can provide with some more logs if needed.

**Comment by mgummelt** [comment]
We spoke over in https://dcos-community.slack.com/messages/data-services/

You shouldn't increase the number of instances.  There's no need.  The jobs launched by the dispatcher will use the entire mesos cluster.
