### ISSUE TITLE
mesosphere/spark:1.1.0-2.1.1-hadoop-2.7 has hadoop 2.6.4

### ISSUE THREAD

**Issue by rozele** [mesosphere/spark-build#153]
As the version tag would suggest, this container is supposed to have hadoop 2.7, but instead it has hadoop 2.6.4.  This is not a problem for earlier versions (e.g., 1.0.9-2.1.0-1-hadoop-2.7 has the correct dependencies)

**Comment by mgummelt** [comment]
Thanks for the report.  I've verified the jars are incorrect.  Fixing...

**Comment by mgummelt** [comment]
Should be fixed. I just overwrote the docker tag, since the hadoop jars should be the only diff.  Let me know if you pull and don't see the changes for some reason.

**Comment by mgummelt** [comment]
source of bug: https://github.com/mesosphere/spark-build/commit/1ed8829e3e2d9c4f8174415a2a4fefc63282b940
