### ISSUE TITLE
Adding hadoop-azure-2.7.3.jar to Spark Docker image

### ISSUE THREAD

**Issue by rozele** [mesosphere/spark-build#154]
I'm trying to connect Spark on DC/OS to Azure Blob Storage via WASB.  In order to do that, I need to ensure hadoop-azure-2.73.jar is on the classpath (along with azure-storage-*.jar).

The documentation states that "_DC/OS Spark does not support arbitrary Spark distributions_" and that you must select a docker image from [here](https://hub.docker.com/r/mesosphere/spark/tags/).  How can I create an extension of the mesosphere/spark Docker container with the req'd jars and use it in the DC/OS Spark package?

**Comment by mgummelt** [comment]
https://github.com/mesosphere/spark-build/blob/master/docs/custom-docker.md
