### ISSUE TITLE
Spark package fails to install with permission errors

### ISSUE THREAD

**Issue by hantuzun** [mesosphere/spark-build#208]
I cannot install Spark on my DC/OS cluster. My DC/OS cluster is created with terraform on Azure.

I installed `hello-world` and `chronos` services successfully, but installing `spark` stucks in deployment stage. 

### System details

```
[user@private-agent-1 ~]$ cat /etc/*release
CentOS Linux release 7.3.1611 (Core)
```

```
[user@private-agent-1 ~]$ dcos --version
dcoscli.version=0.5.5
dcos.version=1.10.1
dcos.commit=d932fc405eb80d8e5b3516eaabf2bd41a2c25c9f
dcos.bootstrap-id=b7c22f7cfb481d9f957a0adfb7e1e719297b9487
```

```
[user@private-agent-1 ~]$ dcos package list
NAME   VERSION        APP     COMMAND  DESCRIPTION
spark  2.1.0-2.2.0-1  /spark  spark    Spark is a fast and general cluster computing system for Big...
```

```
[user@private-agent-1 ~]$ dcos spark run --submit-args="--class org.apache.spark.examples.SparkPi https://downloads.mesosphere.com.s3.amazonaws.com/assets/spark/spark-examples_2.10-1.5.0.jar"

2017/11/21 18:27:51 Using mesosphere/spark:2.1.0-2.2.0-1-hadoop-2.6 as the image for the driver
2017/11/21 18:27:51 Pulling image mesosphere/spark:2.1.0-2.2.0-1-hadoop-2.6 for executors, by default. To bypass set spark.mesos.executor.docker.forcePullImage=false
2017/11/21 18:27:51 Setting DCOS_SPACE to /spark
2017/11/21 18:27:51 Failed to create submission with error Could not reach the service scheduler with name 'spark'.
Did you provide the correct service name? Specify a different name with '--name=<name>'.
Was the service recently installed or updated? It may still be initializing, wait a bit and try again.
```

### Logs

Trace logs of the tasks are always like below:

```
I1121 19:25:04.568644 63081 exec.cpp:162] Version: 1.4.0
I1121 19:25:04.575340 63083 exec.cpp:237] Executor registered on agent c27b0043-ce69-4a22-a76e-36664ea650d8-S0
I1121 19:25:04.576223 63083 executor.cpp:120] Registered docker executor on 10.32.0.7
I1121 19:25:04.576253 63083 executor.cpp:160] Starting task spark.f050b29a-cef1-11e7-9bfa-e6da7bf271b4
+ export DISPATCHER_PORT=7810
+ DISPATCHER_PORT=7810
+ export DISPATCHER_UI_PORT=7811
+ DISPATCHER_UI_PORT=7811
+ export SPARK_PROXY_PORT=7812
+ SPARK_PROXY_PORT=7812
+ SCHEME=http
+ OTHER_SCHEME=https
+ [[ '' == true ]]
+ export DISPATCHER_UI_WEB_PROXY_BASE=/service/spark
+ DISPATCHER_UI_WEB_PROXY_BASE=/service/spark
+ grep -v '#https#' /etc/nginx/conf.d/spark.conf.template
+ sed s,#http#,,
+ sed -i 's,<PORT>,7812,' /etc/nginx/conf.d/spark.conf
+ sed -i 's,<DISPATCHER_URL>,http://10.32.0.7:7810,' /etc/nginx/conf.d/spark.conf
+ sed -i 's,<DISPATCHER_UI_URL>,http://10.32.0.7:7811,' /etc/nginx/conf.d/spark.conf
+ sed -i 's,<PROTOCOL>,,' /etc/nginx/conf.d/spark.conf
+ [[ '' == true ]]
+ [[ -f hdfs-site.xml ]]
+ [[ -n '' ]]
+ exec runsvdir -P /etc/service
+ mkdir -p /mnt/mesos/sandbox/nginx
+ mkdir -p /mnt/mesos/sandbox/spark
+ exec
mkdir: cannot create directory '/mnt/mesos/sandbox/nginx': Permission denied
mkdir: cannot create directory '/mnt/mesos/sandbox/spark': Permission denied
+ mkdir -p /mnt/mesos/sandbox/spark
+ mkdir -p /mnt/mesos/sandbox/nginx
mkdir: cannot create directory '/mnt/mesos/sandbox/spark': Permission denied
mkdir: cannot create directory '/mnt/mesos/sandbox/nginx': Permission denied
(repeat till being killed)
``` 

`2.0.2-2.2.0-1-hadoop-2.7`, `2.1.0-2.2.0-1-hadoop-2.6` and `1.1.1-2.2.0-hadoop-2.6` all got similar permission errors.

### Opinions

It seems like the following two scripts are not called with proper permissions:
https://github.com/mesosphere/spark-build/blob/01e9edf3ceea9580711a4f9cd6f631bedbe1bc30/docker/runit/service/nginx/log/run
https://github.com/mesosphere/spark-build/blob/01e9edf3ceea9580711a4f9cd6f631bedbe1bc30/docker/runit/service/spark/log/run

**Comment by hantuzun** [comment]
I've some updates.

This failure happens when DC/OS is installed with Terraform on Azure using a variation of https://github.com/bernadinm/terraform-dcos and https://github.com/bernadinm/tf_dcos_core.

It didn't happen using a template install of DC/OS on Azure via https://downloads.dcos.io/dcos/stable/azure.html?_ga=2.74635282.1275548549.1511285783-1361358655.1499362214.

I'm failing to detect the cause of the error...

**Comment by lgromanowski** [comment]
Hi,
I have the same issue - DC/OS was installed via Advanced installer method.

**Comment by hantuzun** [comment]
This error might be about Centos. With CoreOS I don't experience this permission error but there're other issues there as well.

**Comment by fbeneventi** [comment]
Hi,
I' experiencing the same issue.

CentOS Linux release 7.4.1708 (Core)
DC/OS version 1.10.0

**Comment by hantuzun** [comment]
Running `chcon -Rt svirt_sandbox_file_t /var/lib/mesos` on the servers resolves this issue on CentOS.

I'm unable to run Spark with Spark logs showing "`exec`" lines repeated hundreds of times before being killed due to healthcheck failures but its not in the context of this issue.

**Comment by fbeneventi** [comment]
Hi,

just an update:

After adding the hostames of the overall cluster in the /etc/hosts of each node I had the Spark service succesfully running in the dcos dashboard and not killed by the heathcheck. 

However the messages 
"mkdir: cannot create directory '/mnt/mesos/sandbox/nginx': Permission denied"
are still there.

I tested the package running example jobs and the spark cluster runs without errors.

**Comment by Chicker** [comment]
Yet another workaround. Just install spark with custom config like this:

```
{
        "service": {
                "user": "root"
        }
}
```

**Comment by lgromanowski** [comment]
@Chicker Thanks, it works! :)

**Comment by leftluoyi** [comment]
edit the service and find 
```
      "parameters": [
        {
          "key": "user",
          "value": "nobody"
        }
      ]
```
change the value to **root** also works.

**Comment by leftluoyi** [comment]
Now I am also seeing the `exec` problem. Marathon says bad gateway problem. Any idea how to fix it?

**Comment by bdonnahue** [comment]
I can confirm that this issue exists on 1.12.0 with spark being installed via the UI and CLI 0.7

**Comment by bdonnahue** [comment]
Any updates here?

**Comment by samvantran** [comment]
Hi @bdonnahue, can you give some more info on what package version/OS you're using? I gave this a try on a fresh cluster and saw it work as expected (but I used CoreOs).

Here was my test:

```
$ cat /etc/*-release
DISTRIB_ID="Container Linux by CoreOS"
DISTRIB_RELEASE=1235.12.0
DISTRIB_CODENAME="Ladybug"
DISTRIB_DESCRIPTION="Container Linux by CoreOS 1235.12.0 (Ladybug)"
...

$ dcos --version
dcoscli.version=0.6.0-dev
dcos.version=1.12.0
dcos.commit=20fa047bbd37188ccb55f61ab9590edc809030ec
dcos.bootstrap-id=51c3e1a0a5b7fdace4abccc998e970df07eb606e
...

$ dcos package install spark --cli --yes
By Deploying, you agree to the Terms and Conditions https://mesosphere.com/catalog-terms-conditions/#certified-services
Installing CLI subcommand for package [spark] version [2.4.0-2.2.1-3]
New command available: dcos spark
...

$ dcos spark run --submit-args="--class org.apache.spark.examples.SparkPi https://downloads.mesosphere.com/spark/assets/spark-examples_2.11-2.0.1.jar 30"
Using image 'mesosphere/spark:2.4.0-2.2.1-3-hadoop-2.6' for the driver and the executors (from dispatcher: container.docker.image).
To disable this image on executors, set spark.mesos.executor.docker.forcePullImage=false
Run job succeeded. Submission id: driver-20181106185205-0004
...

$ dcos task log driver-20181106185205-0004 --completed
spark-env: StatsD metrics require Mesos UCR. For dispatcher metrics, enable the 'UCR_containerizer' option. For driver metrics, include '--conf spark.mesos.containerizer=mesos' in your run
Pi is roughly 3.141151713717238
```

**Comment by bdonnahue** [comment]
Hey @samvantran 

Your commands did not work for me:

`[root@DcosBootstrap ~]# cat /etc/*-release
CentOS Linux release 7.5.1804 (Core)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.5.1804 (Core)
CentOS Linux release 7.5.1804 (Core)
[root@DcosBootstrap ~]# dcos --version
dcoscli.version=0.6.5
dcos.version=1.12.0
dcos.commit=6156e8f5cb2ad123aa25d116795867c49619be72
dcos.bootstrap-id=51c3e1a0a5b7fdace4abccc998e970df07eb606e
[root@DcosBootstrap ~]# dcos package install spark --cli --yes
By Deploying, you agree to the Terms and Conditions https://mesosphere.com/catalog-terms-conditions/#certified-services
Installing CLI subcommand for package [spark] version [2.4.0-2.2.1-3]
New command available: dcos spark
[root@DcosBootstrap ~]# dcos spark run --submit-args="--class org.apache.spark.examples.SparkPi https://downloads.mesosphere.com/spark/assets/spark-examples_2.11-2.0.1.jar 30"
dcos-spark: error: unable to find key 'app' in map: map[message:App '/spark' does not exist], try --help
`

**Comment by bdonnahue** [comment]
@samvantran no its the same result (same error message)

**Comment by bdonnahue** [comment]
@samvantran can you post your configs from the bootstrap node?

**Comment by bdonnahue** [comment]
@samvantran ahh, i am not on aws... Maybe i can configure terraform to deploy on cloudstack instead

**Comment by bdonnahue** [comment]
how was this issue closed? I am still not able to install etc
