### ISSUE TITLE
Spark 2.3.0 build

### ISSUE THREAD

**Issue by tedmiston** [mesosphere/spark-build#304]
Hi - I'm wondering if there are plans to publish a build that includes Spark 2.3.0?

It looks like the current master is [pulling Spark 2.2.1](https://github.com/mesosphere/spark-build/blob/920e1910a535ff9f2c7f745d14dcfd2cd2d38955/manifest.json#L15).

Spark 2.3.0 was release February 28, 2018 and release notes are available [here](https://spark.apache.org/news/spark-2-3-0-released.html).

**Comment by samvantran** [comment]
Hi @tedmiston, it's in the works but not for another month or two.

**Comment by vishnu2kmohan** [comment]
@tedmiston We're actively working to release Spark 2.3.2

**Comment by samvantran** [comment]
We've released versions 2.3.2 and 2.4.0 : https://docs.mesosphere.com/services/spark/
