### ISSUE TITLE
Check and update row by row in spark java

### ISSUE THREAD

**Issue by harithareddy051** [mesosphere/spark-build#339]
I have generated an XML file using JAXB in java

<AutoRuleDetails>
<saveMode>OVERWRITE</saveMode>
    <Rules>
        <Ruleconfiguration>
            <BusinessRule>
                <AttributeCondition>
                    <AttributeName>TEMPB</AttributeName>
                    <AttributeValue>10</AttributeValue>
                </AttributeCondition>
                <AttributeCondition>
                    <AttributeName>TEMPC</AttributeName>
                    <AttributeValue>19</AttributeValue>
                </AttributeCondition>

            </BusinessRule>
            <CleansingAttribute>ATTP</CleansingAttribute>
            <CleansingValue>0</CleansingValue>

         </Ruleconfiguration>
    </Rules>
</AutoRuleDetails>  
Based on this XML I'm trying to update cleansingAttribute and cleansing values i.e., when TEMPB=10 and TEMPC=19 then set ATTP=0 Basically I need to iterate through every row in the dataframe,check the attribute name and values and based on that update cleansing attribute and values

For this I'm trying to use map

return df.toJavaRDD().map(new Function<Row,Row>(){
@Override
public Row call(Row row) throws Exception{
//unable to get the logic for check and update

}
Can anybody help me with this.

**Comment by elezar** [comment]
This repository is not geared towards general Spark questions, and only addresses running Spark on DC/OS. See one of the community resources for the Apache Spark project directly: https://spark.apache.org/community.html
