### ISSUE TITLE
Locally building fails

### ISSUE THREAD

**Issue by wjglerum** [mesosphere/spark-build#493]
I tried building this project locally to give spark 2.4.0 a try. I followed the README, however the Makefile doesn't work for me. Did I miss anything?

1. `make docker-build` works and a container is created
2. `make prod-dist` fails with:
```
/bin/bash: ./dev/make-distribution.sh: No such file or directory
make: *** [prod-dist] Error 127
```

**Comment by akirillov** [comment]
Hi @wjglerum, just to clarify `prod-dist` step is used to checkout Apache Spark sources and build a dist tarball for the future use with Dockerfile. Are you using a custom `SPARK_DIR` for the build? Is it an absolute path? Also, which version of `make` are you using?

If `SPARK_DIR`is not provided then `mesosphere/spark` master branch will be used which is a bit off of the upstream. You can try to checkout [custom-branch-2.4.x](https://github.com/mesosphere/spark/tree/custom-branch-2.4.x) which has all the latest changes and tested with all supported DCOS clusters. 

So the whole process should look that:
```
mkdir dcos-spark 
cd dcos-spark
export DIR_PATH=$(pwd)

git clone git@github.com:mesosphere/spark.git
cd spark
git checkout custom-branch-2.4.x
cd ..

git clone git@github.com:mesosphere/spark-build.git
cd spark-build

SPARK_DIR=${DIR_PATH}/spark make prod-dist
```

**Comment by wjglerum** [comment]
Hi, thank you for your reply. I will try to test it again. For now Spark 2.4.0 is available already in the catalog so we are fine ;)
