### ISSUE TITLE
Cannot pull image mesosphere/mesos-modules-private:git-e348e3f

### ISSUE THREAD

**Issue by rickalm** [mesosphere/spark-build#56]
Can't build the container without the base image

**Comment by mooperd** [comment]
+1

**Comment by joerg84** [comment]
@mgummelt

**Comment by mgummelt** [comment]
We're aware and looking for a better solution.  The best way to extend the image right now is probably just to extend from the latest published image (mesosphere/spark:1.0.2-2.0.0)

**Comment by elyast** [comment]
any progress ?

**Comment by mgummelt** [comment]
Sorry, this issue got away from me.  I'll ping the Mesos team about making this public, but in the mean time, is there something you're trying to do that can't be done by just extending the Spark image?

**Comment by elyast** [comment]
Nope not really, we solved our issue with extending from mesosphere/spark, however it would give more flexibility to customize spark package / JRE version, etc

**Comment by rajeshwer** [comment]
i have the same issue there are some missing libraries like lzo and lzop so i wanted to add them and bild but its failing cause mesosphere/mesos-modules-private:dcos-ee-mesos-modules-1.8.5-rc2 was not available

**Comment by yuchaoran2011** [comment]
I'm facing the same issue here. Can Mesosphere make the base image public?

**Comment by skonto** [comment]
@susanxhuynh is this still the case?

**Comment by susanxhuynh** [comment]
This is no longer the case, @skonto . We now extend from `ubuntu` and download the Mesos library. Closing.
