### ISSUE TITLE
Spark CLI plugin for MacOS Catalina

### ISSUE THREAD

**Issue by piyushgup** [mesosphere/spark-build#562]
Hi,

I have been using the dcos-spark plugin on macos for deploying spark applications. I recently upgraded to catalina and the plugin stopped working, with the error:

```Bad CPU type in executable```

On investigating further, i found that the dcos-spark executable is 32 bit

Is it possible to publish a 64 bit MacOS version of the dcos-spark plugin to work with MacOs Catalina like platforms?

**Comment by MikaelZulfigarov** [comment]
Also having this one on my mac. Is there any workaround or smth?
