### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by oxynad** [mesosphere/spark-build#95]
### DC/OS version: 1.8.6

When trying to install spark in the DC/OS cli, I get the following error:

> Installing Marathon app for package [spark] version [1.0.4-2.0.1]
> Installing CLI subcommand for package [spark] version [1.0.4-2.0.1]
> MainThread: 2016-11-12 13:41:11,899 dcos/subcommand.py:_execute_command:587 - Command script's stderr: b'/Users/oxynad/.dcos/subcommands/spark/env/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.\n  SNIMissingWarning\n/Users/oxynad/.dcos/subcommands/spark/env/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.\n  InsecurePlatformWarning\nException:\nTraceback (most recent call last):\n  File "/Users/oxynad/.dcos/subcommands/spark/env/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main\n    status = self.run(options, args)\n  File "/Users/oxynad/.dcos/subcommands/spark/env/lib/python2.7/site-packages/pip/commands/install.py", line 335, in run\n    wb.build(autobuilding=True)\n  File "/Users/oxynad/.dcos/subcommands/spark/env/lib/python2.7/site-packages/pip/wheel.py", line 749, in build\n    self.requirement_set.prepare_files(self.finder)\n  File "/Users/oxynad/.dcos/subcommands/spark/env/lib/python2.7/site-packages/pip/req/req_set.py", line 380, in prepare_files\n    ignore_dependencies=self.ignore_dependencies))\n  File "/Users/oxynad/.dcos/subcommands/spark/env/lib/python2.7/site-packages/pip/req/req_set.py", line 620, in _prepare_file\n    session=self.session, hashes=hashes)\n  File "/Users/oxynad/.dcos/subcommands/spark/env/lib/python2.7/site-packages/pip/download.py", line 821, in unpack_url\n    hashes=hashes\n  File "/Users/oxynad/.dcos/subcommands/spark/env/lib/python2.7/site-packages/pip/download.py", line 659, in unpack_http_url\n    hashes)\n  File "/Users/oxynad/.dcos/subcommands/spark/env/lib/python2.7/site-packages/pip/download.py", line 853, in _download_http_url\n    stream=True,\n  File "/Users/oxynad/.dcos/subcommands/spark/env/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 488, in get\n    return self.request(\'GET\', url, **kwargs)\n  File "/Users/oxynad/.dcos/subcommands/spark/env/lib/python2.7/site-packages/pip/download.py", line 386, in request\n    return super(PipSession, self).request(method, url, *args, **kwargs)\n  File "/Users/oxynad/.dcos/subcommands/spark/env/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 475, in request\n    resp = self.send(prep, **send_kwargs)\n  File "/Users/oxynad/.dcos/subcommands/spark/env/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 596, in send\n    r = adapter.send(request, **kwargs)\n  File "/Users/oxynad/.dcos/subcommands/spark/env/lib/python2.7/site-packages/pip/_vendor/cachecontrol/adapter.py", line 47, in send\n    resp = super(CacheControlAdapter, self).send(request, **kw)\n  File "/Users/oxynad/.dcos/subcommands/spark/env/lib/python2.7/site-packages/pip/_vendor/requests/adapters.py", line 497, in send\n    raise SSLError(e, request=request)\nSSLError: [Errno 1] _ssl.c:507: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure\n'

It ends by saying that: **"Error installing 'spark' package."**.

**Comment by vishnu2kmohan** [comment]
Would you try again after running:
dcos config set core.ssl_verify false

**Comment by oxynad** [comment]
Core.ssl_verify was already set to false.

**Comment by vishnu2kmohan** [comment]
Are you running the latest versions of the DC/OS (0.4.14) and Spark CLI:

$ dcos --version
dcoscli.version=0.4.14
dcos.version=N/A
dcos.commit=N/A
dcos.bootstrap-id=N/A

$ dcos spark --version
dcos-spark version 0.5.19

**Comment by oxynad** [comment]
The DC/OS version I am using is indeed 0.4.14.

Please see my edit in my post.
